from PIL import Image
import streamlit as st
##Création de liste deroulante pour selectionner le jours:
st.header("Choississez votre jour d'entrainement :")
semaine = st.selectbox("Jour de la semaine",('Lundi','Mardi','Mercredi','Vendredi'))
if semaine == 'Lundi' : 
    st.subheader('_1-Cardio_ : ')
    st.write(':blue[Tapis de course :] 30 min (avec ou sans pente)')
    st.write(':blue[Velo élliptique :] 15 min (alterner 1 min rapide et 30s de repos)')
    st.write(':blue[Vélo ou Escalier :] 20 min')
    st.write(':blue[rameur :] 20 min')
    trapèzes = open('rame.mp4', 'rb')
    trp_bytes = trapèzes.read()
    st.video(trp_bytes)
    st.subheader("_2-Musculation dos et abdominaux_ :")
    st.write(" a) Traction à la Poulie haute prise supination :  4 series de 8 ou 12 répétitions")
    traction = Image.open('tirage_poitrine.jpg')
    st.image(traction)
    trapèzes = open('PPH.mp4', 'rb')
    trp_bytes = trapèzes.read()
    st.video(trp_bytes)
    st.write ('Alternative avec une machine chest press')
    trapèzes = open('vertical.mp4', 'rb')
    trp_bytes = trapèzes.read()
    st.video(trp_bytes)
    st.write("b) Rowing assis à la poulie prise neutre : 4 séries de 8  ou 12 répétitions")
    rowing_assis = Image.open('tirage assis neutre.jpeg')
    st.image(rowing_assis)
    st.write('ancien')
    trapèzes = open('DAP.mp4', 'rb')
    trp_bytes = trapèzes.read()
    st.video(trp_bytes)
    st.write('nouveau')
    trapèzes = open('TH.mp4', 'rb')
    trp_bytes = trapèzes.read()
    st.video(trp_bytes)
    st.write("c) Rowing assis à la poulie basse à un bras : 3 séries de 8 ou 12 répétitions  – Récupération d’une minute entre chaque bras")
    rowing_basse = Image.open('tirage assis  un bras.gif')
    st.image(rowing_basse)
    trapèzes_bras = open('AMP.mp4', 'rb')
    trpbr_bytes = trapèzes_bras.read()
    st.video(trpbr_bytes)
    st.write('alternative avec haltère')
    trapèzes_bras = open('RH.mp4', 'rb')
    trpbr_bytes = trapèzes_bras.read()
    st.video(trpbr_bytes)
    st.write("d) Enroulement / deroulement des lombaires au bancs : 3 series avec 6 ou 10 répétitions ")
    enrouler = Image.open('extension-lombaire-au-banc.jpg')
    st.image(enrouler)
    dos = open('dos.mp4', 'rb')
    dos_bytes = dos.read()
    st.video(dos_bytes)
    st.write('avec une machine assisté')
    dos = open('EL.mp4', 'rb')
    dos_bytes = dos.read()
    st.video(dos_bytes)
    st.write("d) Crunch à la machine : 4 series de 10 ou 15 répétitions")
    crunch_machine = Image.open('crunch-machine.jpg')
    st.image(crunch_machine)
    crunch = open('crunch.mp4', 'rb')
    crunch_bytes = crunch.read()
    st.video(crunch_bytes)
    st.write("e) Planche : 4 series de 10 répétitions")
    planche = Image.open('planche.jpg')
    st.image(planche)
    crunch = open('planche.mp4', 'rb')
    crunch_bytes = crunch.read()
    st.video(crunch_bytes)
    st.title(":red[Important : 5 min d'étirements à la fin de la séance et s'hydrater.]")
if semaine == 'Mardi' :
    st.subheader('_1-Cardio_ : ')
    st.write(':blue[Tapis de course :] 30 min (avec ou sans pente)')
    st.write(':blue[Velo élliptique :] 15 min (alterner 1 min rapide et 30s de repos)')
    st.write(':blue[Vélo ou Escalier :] 20 min')
    st.write(':blue[rameur :] 20 min')
    trapèzes = open('rame.mp4', 'rb')
    trp_bytes = trapèzes.read()
    st.video(trp_bytes)
    st.subheader("_2-Musculation épaules et triceps_ :")
    st.write("a) Développé avec haltères : 4 series de 8 ou 12 répétitions")
    developpe_halt = Image.open('developpé haltère.jpg')
    st.image(developpe_halt)
    halteres = open('ET.mp4', 'rb')
    halteres_bytes = halteres.read()
    st.video(halteres_bytes)
    st.write('Alternative avec machine triceps ')
    halteres = open('ST.mp4', 'rb')
    halteres_bytes = halteres.read()
    st.video(halteres_bytes)
    st.write("b) Rowing debout à la poulie basse : 4 séries de 10 ou 15 répétitions")
    rowing_debout = Image.open('rowing debout poulie basse.png')
    st.image(rowing_debout)
    rdb = open('rdb.mp4', 'rb')
    rdb_bytes = rdb.read()
    st.video(rdb_bytes)
    st.write('alternative machine ')
    rdb = open('DM.mp4', 'rb')
    rdb_bytes = rdb.read()
    st.video(rdb_bytes)
    st.write("c) Rowing à la poulie haute sur banc incliné coudes ouverts : 4 séries de 10 ou 15 répétitions")
    rowing_haute = Image.open('rowing incliné.jpg')
    st.image(rowing_haute)
    rdb_coudes = open('rdb_coudes.mp4', 'rb')
    rdb_coudes_bytes = rdb_coudes.read()
    st.video(rdb_coudes_bytes)
    st.write ('alternative avec dual adjustable pulley')
    rdb_coudes = open('EP.mp4', 'rb')
    rdb_coudes_bytes = rdb_coudes.read()
    st.video(rdb_coudes_bytes)
    st.write("d) L-Fly allongé à la poulie basse : 4 series de 15 ou 20 répétitions")
    l_fly = Image.open('l fly.jpg')
    st.image(l_fly)
    fly = open('fly.mp4', 'rb')
    fly_bytes = fly.read()
    st.video(fly_bytes)
    st.write('alternative avec dual adjustable pulley avec les deux bras ')
    fly = open('pecto.mp4', 'rb')
    fly_bytes = fly.read()
    st.video(fly_bytes)
    st.write("e) Dips à la machine : 4 series avec 8 ou 12 répétitions")
    dm = Image.open('dim.jpg')
    st.image(dm)
    dips = open('CD.mp4', 'rb')
    dips_bytes = dips.read()
    st.video(dips_bytes)
    st.write("f) Pull over Press : 4 series de 10 ou 15 répétitions")
    pull = Image.open('popim.jpg')
    st.image(pull)
    pop = open('pop.mp4', 'rb')
    pop_bytes = pop.read()
    st.video(pop_bytes)
    st.write('alternative avec dap')
    pop = open('TF.mp4', 'rb')
    pop_bytes = pop.read()
    st.video(pop_bytes)
    st.title(":red[Important : 5 min d'étirements à la fin de la séance et s'hydrater.]")
if semaine == 'Mercredi' : 
    st.subheader('_1-Cardio_ : ')
    st.write(':blue[Tapis de course :] 30 min (avec ou sans pente)')
    st.write(':blue[Velo élliptique :] 15 min (alterner 1 min rapide et 30s de repos)')
    st.write(':blue[Vélo ou Escalier :] 20 min')
    st.write(':blue[rameur :] 20 min')
    trapèzes = open('rame.mp4', 'rb')
    trp_bytes = trapèzes.read()
    st.video(trp_bytes)
    st.subheader("_2-Musculation cuisses, mollets, abdominaux_ :")
    st.write("a) Presse à cuisse incliné : 4 series de 8 ou 12 repétitions")
    presse = Image.open('presse à cuisse.jpg')
    st.image(presse)
    quadri = open('pressl.mp4', 'rb')
    quadri_bytes = quadri.read()
    st.video(quadri_bytes)
    st.write("b) Hack squat à la machine : 4 series de 8 ou 12 repétitions")
    squat = Image.open('hack squat.jpg')
    st.image(squat)
    hack = open('hack.mp4', 'rb')
    hack_bytes = hack.read()
    st.video(hack_bytes)
    st.write('alternative avec les altères')
    hack = open('GS.mp4', 'rb')
    hack_bytes = hack.read()
    st.video(hack_bytes)
    st.write("c) Leg curl debout à une jambe : 4 series de 8 ou 12 repétitions")
    leg_curl = Image.open('leg curl.jpg')
    st.image(leg_curl)
    leg = open('leg.mp4', 'rb')
    leg_bytes = leg.read()
    st.video(leg_bytes)
    st.write('alternative machine')
    leg = open('curlleg.mp4', 'rb')
    leg_bytes = leg.read()
    st.video(leg_bytes)
    st.write("d) Soulevé de terre jambes tendues : 4 series de 8 ou 12 repétitions")
    soulevé = Image.open('soulevé de terre.jpg')
    st.image(soulevé)
    stj = open('stj.mp4', 'rb')
    stj_bytes = stj.read()
    st.video(stj_bytes)
    st.write('alternative avec altère')
    stj = open('DL.mp4', 'rb')
    stj_bytes = stj.read()
    st.video(stj_bytes)
    st.write("e) Chameau : 8 series de 10 ou 15 repétitions")
    chameau = open('chameau.mp4', 'rb')
    chameau_bytes = chameau.read()
    st.video(chameau_bytes)
    st.write("f) Crunch avec dual adjustable pulley : 4 series de 10 ou 15 repétitions")
    crunch_ab = Image.open('crunch abmat.jpg')
    st.image(crunch_ab)
    abmat = open('cr.mp4', 'rb')
    abmat_bytes = abmat.read()
    st.video(abmat_bytes)
    st.title(":red[Important : 5 min d'étirements à la fin de la séance et s'hydrater.]")
if semaine == 'Vendredi' :
    st.subheader('_1-Cardio_ : ')
    st.write(':blue[Tapis de course :] 30 min (avec ou sans pente)')
    st.write(':blue[Velo élliptique :] 15 min (alterner 1 min rapide et 30s de repos)')
    st.write(':blue[Vélo ou Escalier :] 20 min')
    st.write(':blue[rameur :] 20 min')
    trapèzes = open('rame.mp4', 'rb')
    trp_bytes = trapèzes.read()
    st.video(trp_bytes)
    st.subheader("_2-Musculation pectoraux et biceps_ :")
    st.write("a) Développé incliné : 8 series de 8 ou 12 repétitions")
    d_in = Image.open('developpe incliné.jpg')
    st.image(d_in)
    developpe = open('developpe.mp4', 'rb')
    developpe_bytes = developpe.read()
    st.video(developpe_bytes)
    st.write("b) Écarté à la poulie vis-à-vis haute : 3 séries de 10 ou 15 répétitions")
    ecarte = Image.open('ecarté poulie.jpg')
    st.image(ecarte)
    eph = open('eph.mp4', 'rb')
    eph_bytes = eph.read()
    st.video(eph_bytes)
    st.write('alternative avec dual adjustable pulley ')
    fly = open('pecto.mp4', 'rb')
    fly_bytes = fly.read()
    st.video(fly_bytes)
    st.write("c) Late pull down au sol : 4 séries de 10 répétitions")
    late = Image.open('late pull down.jpg')
    st.image(late)
    lpd = open('upper.mp4', 'rb')
    lpd_bytes = lpd.read()
    st.video(lpd_bytes)
    st.write("d) curl au haltères : 4 séries de 10 répétitions")
    curl_halt = Image.open('curl altère.jpg')
    st.image(curl_halt)
    curl = open('curl.mp4', 'rb')
    curl_bytes = curl.read()
    st.video(curl_bytes)
    st.write('Alternative avec dual adjustable pulley')
    curl = open('CP.mp4', 'rb')
    curl_bytes = curl.read()
    st.video(curl_bytes)
    st.title(":red[Important : 5 min d'étirements à la fin de la séance et s'hydrater.]")
